Himall.Web/Areas/Admin/Controllers/ShopGradeController.cs
using Himall.IServices;
using Himall.Model;
using Himall.Web.Framework;
using Himall.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web.Mvc;

namespace Himall.Web.Areas.Admin.Controllers
{
	public class ShopGradeController : BaseAdminController
	{
		public ShopGradeController()
		{
		}

		[HttpGet]
		public ActionResult Add()
		{
			return View();
		}

		[HttpPost]
		[UnAuthorize]
		public ActionResult Add(ShopGradeModel shopG)
		{
			if (!base.ModelState.IsValid)
			{
				return View(shopG);
			}
			ServiceHelper.Create<IShopService>().AddShopGrade(shopG);
			return RedirectToAction("Management");
		}

		[HttpPost]
		[UnAuthorize]
		public JsonResult DeleteShopGrade(long id)
		{
			string str = "";
			ServiceHelper.Create<IShopService>().DeleteShopGrade(id, out str);
			if (string.IsNullOrWhiteSpace(str))
			{
				return Json(new { Successful = true });
			}
			return Json(new { Successful = false, msg = str });
		}

		[HttpPost]
		[UnAuthorize]
		public ActionResult Edit(ShopGradeModel shopG)
		{
			if (!base.ModelState.IsValid)
			{
				return View(shopG);
			}
			ServiceHelper.Create<IShopService>().UpdateShopGrade(shopG);
			return RedirectToAction("Management");
		}

		[HttpGet]
		public ActionResult Edit(long id)
		{
			return View(new ShopGradeModel(ServiceHelper.Create<IShopService>().GetShopGrade(id)));
		}

		[HttpPost]
		[UnAuthorize]
		public JsonResult List()
		{
			IQueryable<ShopGradeInfo> shopGrades = ServiceHelper.Create<IShopService>().GetShopGrades();
			IEnumerable<ShopGradeModel> array = 
				from item in shopGrades.ToArray()
                select new ShopGradeModel()
				{
					Id = item.Id,
					ChargeStandard = item.ChargeStandard,
					ImageLimit = item.ImageLimit,
					ProductLimit = item.ProductLimit,
					Name = item.Name
				};
			DataGridModel<ShopGradeModel> dataGridModel = new DataGridModel<ShopGradeModel>()
			{
				rows = array,
				total = shopGrades.Count()
			};
			return Json(dataGridModel);
		}

		public ActionResult Management()
		{
			return View();
		}
	}
}

Himall.Web/Areas/Admin/Views/ShopGrade/Add.cshtml
@model Himall.Web.Models.ShopGradeModel

@{
    ViewBag.Title = "Add";
}
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script type="text/javascript">

    $(function () {
        $("#Name").focus();
        $("#shopGSubmit").click(function () {
        });
    });
</script>

<div class="container">
    <ul class="nav nav-tabs-custom clearfix">
        <strong>店铺套餐</strong>
        <li><a href="./Management">管理</a></li>
        <li class="active"><a>新增</a></li>
        <em class="primary-btn">
            <span class="glyphicon glyphicon-question-sign"></span>
            <div class="primary">
                <h3>温馨提示：</h3>
                <span>*</span><p>添加店铺套餐</p>
            </div>
        </em>
    </ul>
    @using (Html.BeginForm("Add", "ShopGrade", new { Area = "Admin" }, FormMethod.Post, new { id = "ShopGradeForm" }))
    {
        <div class="form-horizontal">
            <div class="form-group">
            
                <label class="col-sm-2 control-label" for="">套餐名称：</label>
                <div class="col-sm-3">@Html.EditorFor(s => s.Name, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-3">@Html.ValidationMessageFor(s => s.Name, "", new { @class = "help-default cor-red" })</div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">可发布商品数：</label>
                <div class="col-sm-3">@Html.EditorFor(s => s.ProductLimit, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-3">@Html.ValidationMessageFor(s => s.ProductLimit, "", new { @class = "help-default cor-red" })</div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">可用空间（M）：</label>
                <div class="col-sm-3">@Html.EditorFor(s => s.ImageLimit, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-3">@Html.ValidationMessageFor(s => s.ImageLimit, "", new { @class = "help-default cor-red" })</div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">年费：</label>
                <div class="col-sm-3">@Html.EditorFor(s => s.ChargeStandard, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-3">元 &nbsp;&nbsp; @Html.ValidationMessageFor(s => s.ChargeStandard, "", new { @class = "help-default cor-red" })</div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary" id="shopGSubmit">保 存</button>
                </div>
            </div>
        </div>
    }

</div>

@*<script>
    $(function () {
        $('#Name').blur(function () {
            var name = $.trim($('#Name').val());
            var reg = /^[a-zA-Z0-9\u4e00-\u9fa5]+$/;
            if (!name) {
                $("#nameTip").text("请输入关联板式的名称！");
                $('input[name="name"]').css({ border: '1px solid #f60' });
                $('input[name="name"]').focus();
                return false;
            }
            if (reg.test(name) == false) {
                $("#nameTip").text("名称必须是中文，字母，数字！");
                $('input[name="name"]').css({ border: '1px solid #f60' });
                $('input[name="name"]').focus();
                return false;
            }

            if (name.length > 30) {
                $("#nameTip").text("名称最多只能输入30个字符！");
                $('input[name="name"]').css({ border: '1px solid #f60' });
                $('input[name="name"]').focus();
                return false;
            }
            else {
                $("#nameTip").text("");
                $('input[name="name"]').css({ border: '1px solid #ccc' });
            }
        })
    })
</script>*@

Himall.Web/Areas/Admin/Views/ShopGrade/Edit.cshtml
@model Himall.Web.Models.ShopGradeModel

@{
    ViewBag.Title = "Edit";
}
<script type="text/javascript">

    $(function () {
	$("#Name").focus();
    });
</script>
<div class="container">
    <ul class="nav nav-tabs-custom clearfix">
        <strong>店铺套餐</strong>
        <li><a href="./Management">管理</a></li>
        <li class="active"><a>编辑</a></li>
        <em class="primary-btn">
            <span class="glyphicon glyphicon-question-sign"></span>
            <div class="primary">
                <h3>温馨提示：</h3>
                <span>*</span><p>修改店铺套餐</p>
            </div>
        </em>
    </ul>
    @using (Html.BeginForm("Edit", "ShopGrade", new { Area = "Admin" }, FormMethod.Post))
    {
        @Html.HiddenFor(s => s.Id)
        <div class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">套餐名称</label>
                <div class="col-sm-3">@Html.EditorFor(s => s.Name, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-3">@Html.ValidationMessageFor(s => s.Name, "", new { @class = "help-default cor-red" })</div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">可发布商品数</label>
                <div class="col-sm-3">@Html.EditorFor(s => s.ProductLimit, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-3">@Html.ValidationMessageFor(s => s.ProductLimit, "", new { @class = "help-default cor-red" })</div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">可用空间（M）</label>
                <div class="col-sm-3">@Html.EditorFor(s => s.ImageLimit, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-3">@Html.ValidationMessageFor(s => s.ImageLimit, "", new { @class = "help-default cor-red" })</div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="">年费</label>
                <div class="col-sm-3">@Html.EditorFor(s => s.ChargeStandard, new { htmlAttributes = new { @class = "form-control input-sm" } })</div>
                <div class="col-sm-3">元 &nbsp;&nbsp; @Html.ValidationMessageFor(s => s.ChargeStandard, "", new { @class = "help-default cor-red" })</div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>

    }

    </div>

Himall.Web/Areas/Admin/Views/ShopGrade/Management.cshtml
@{
    ViewBag.Title = "Management";
}
<script src="~/Scripts/jquery.hiMallDatagrid.js"></script>
<script src="~/Scripts/CommonJS.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

<script type="text/javascript">

    function deleteShopGradeEvent(id) {
        $.dialog.confirm('您确定要删除该店铺套餐吗？', function () {
            var loading = showLoading();
            ajaxRequest({
                type: 'POST',
                url: './DeleteShopGrade',
                cache: false,
                param: { Id: id },
                dataType: 'json',
                success: function (data) {
                    loading.close();
                    if (data.Successful == true) {
                        location.href = './Management';
                    } else {
                        $.dialog.errorTips(data.msg);
                    }
                },
                error: function (data) {
                    loading.close(); $.dialog.tips('删除失败,请稍候尝试.');
                }
            });
        });
    }

    function Query() {


        $("#shopGradeDatagrid").hiMallDatagrid({
            url: "./List",
            singleSelect: true,
            pagination: false,
            NoDataMsg: '没有找到符合条件的数据',
            idField: "Id",
            pageSize: 5,
            pageNumber: 1,
            queryParams: {},
            toolbar: "",
            columns:
            [[

                { field: "Id", title: "Id", hidden: true },
                { field: "Name", title: "套餐名称", width: 140 },
                { field: "ProductLimit", title: "可发布商品", width: 180 },
                { field: "ImageLimit", title: "可使用空间(M)", width: 180 },
                { field: "ChargeStandard", title: "年费", width: 180 },
                {
                    field: "operation", operation: true, title: "操作",
                    formatter: function (value, row, index) {
                        var id = row.Id.toString();
                        var html = ['<span class="btn-a">'];
                        html.push('<a href="./Edit?id=' + id + '">编辑</a>');
                        //html.push('<a onclick="deleteShopGradeEvent(' + id + ');">删除</a>');
                        html.push("</span>");

                        return html.join("");
                    }
                }
            ]]
        });

    };

    $(function () {

        Query();

        //新增套餐
        $('#AddShopG').click(function () {
            $.dialog.open('./Add', {
                title: '新增套餐',
                id: 'addPackage',
                lock: true,
                okVal: '保存',
		init:function(){},
                ok: function () {
                    var iframe = this.iframe.contentWindow;
                    var form=iframe.document.getElementById("ShopGradeForm");
                    if ($(form).valid()) {
                        $(form).submit();
                    } else {
                        return false;
                    }
                }
            })
        });
    });
</script>

<div class="container">
    <ul class="nav nav-tabs-custom clearfix">
        <strong>店铺套餐</strong>
        <li class="active"><a>管理</a></li>
        <li><a href="./Add">新增</a></li>
        <em class="primary-btn">
            <span class="glyphicon glyphicon-question-sign"></span>
            <div class="primary">
                <h3>温馨提示：</h3>
                <span>*</span><p>管理平台所有的店铺套餐</p>
            </div>
        </em>
    </ul>
    <table class="table mt20" id="shopGradeDatagrid"></table>

</div>